feat: generate Docker image SBOM
cds-snc/security-tools pull request #15
Opened 2022-05-17 18:53 UTC by patheard

# Summary
Use the `docker sbom` command to generate a CycloneDX
format BOM.

Optionally support logging into an AWS ECR first so that
the image can be pulled.

# Related
* cds-snc/platform-sre-security-support#94

2022-05-17 18:56 UTC, mohamed-cds requested changes
Do we want to deprecate access keys and instead have teams setup OIDC to this repo that has read access ?

2022-05-17 18:59 UTC, patheard commented
> Do we want to deprecate access keys and instead have teams setup OIDC to this repo that has read access ?

I'm game to set that up - be a good exercise to get that rolled out across the projects

2022-05-18 14:59 UTC, patheard commented on .github/workflows/generate_sbom.yml
> +        if: inputs.project_type ='docker' && inputs.iam_role_to_assume != '' && inputs.iam_role_session_name != ''
One tiny gotcha - we need the double `==` for the first check:
```
inputs.project_type == 'docker'
```

2022-05-18 15:00 UTC, patheard commented on .github/workflows/generate_sbom.yml
> +        if: inputs.project_type ='docker' && inputs.iam_role_to_assume != '' && inputs.iam_role_session_name != ''
same double `==` gotcha

2022-05-18 15:05 UTC, dinophile approved these changes
Well it certainly looks good to me! :shipit:

2022-05-18 15:05 UTC, mohamed-cds approved these changes
real nice! 🚀 ✅

2022-05-18 15:06 UTC, merged